export const ADD_TO_LIST = "ADD_TO_LIST";
export const ADD_TO_READ = "ADD_TO_READ";
export const ADD_COMMENT_ABOUT_BOOK = "ADD_COMMENT_ABOUT_BOOK";
export const SEARCH_BOOK_LIST = "SEARCH_BOOK_LIST";
export const DELETE_COMMENT_ABOUT_BOOK = "DELETE_COMMENT_ABOUT_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";